title: Alexander Bahlk # your name (or website title) here
logo: "/images/Alexander_Bahlk.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Product Owner @ HeyJobs 
  <br><br>
  Interested in groups, projects, and contacts around #greentech, #urbangardening, #sustainability, #biophilic, and #climatechange  
  <br><br>
  * [Self-watering Plant Pot Device using Arduino](#self-watering-plant-pot-device-using-arduino)
  * [Klara](#klara)
  * [WeSource](#wesource)
  * [HeyJobs 2016-2017](#heyjobs-2016-2017)
  * [Football Clash](#football-clash)
  * [Memorado - Brain Training App](#memorado---brain-training-app)
      + [Web games](#web-games)
      + [Mobile apps](#mobile-apps)
  * [Goodgame Galaxy](#goodgame-galaxy)
  * [Goodgame Hercules](#goodgame-hercules)
  * [Goodgame Heroes](#goodgame-heroes)
  * [Goodgame Mafia and Gangster](#goodgame-mafia-and-gangster)
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-bahlk/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
markdown: kramdown
