title: Alexander Bahlk # your name (or website title) here
logo: "/images/Alexander_Bahlk.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Director of Product @ <a href="https://getproductpeople.com/">Product People </a>
 <br><br>
 Product Leader with over 9 years of experience in building, shipping, and scaling digital products as well as hiring and coaching product teams. Experience in digital health (Klara), HR-Tech (HeyJobs, WeSource as co-founder and CTO), gamification (Goodgame Studios, Memorado, Blinkist), IoT (Emma), social networks (nebenan.de), and marketplaces (AVIV Group).
<br><br>
Interested in groups, projects, and contacts around #productmanagement #greentech, #urbangardening, #sustainability, #biophilic, and #climatechange
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-bahlk/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
markdown: kramdown
google_analytics: G-Y2JE06DDW2
